version: '3.3'

services:
  web:
    build:
      context: ./marketplace
      dockerfile: Dockerfile.prod
    command: gunicorn marketplace.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    expose:
      - 8000
    depends_on:
      - db
  db:
    image: postgres:11.14-bullseye
    environment:
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=db
    ports:
      - 5432:5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 80:80
    depends_on:
      - web
  redis:
    image: redis:5-alpine
  celery:
    build:
      context: ./marketplace
      dockerfile: Dockerfile.prod
    command: celery -A marketplace worker -P eventlet
    volumes:
      - ./marketplace:/usr/src/app
    depends_on:
      - web
      - redis
  dashboard:
    build:
      context: ./marketplace
      dockerfile: Dockerfile.prod
    command: celery -A marketplace flower
    ports:
      - 5555:5555
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres_data:
  static_volume:
  media_volume:
  marketplace: