# Generated by Django 4.1.4 on 2023-07-29 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('logo', models.ImageField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('title', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('education_level', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('link', models.URLField()),
                ('grade', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UniversitySpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_places', models.IntegerField()),
                ('contract_places', models.IntegerField()),
                ('budget_passing_score', models.IntegerField()),
                ('contract_passing_score', models.IntegerField()),
                ('price', models.IntegerField()),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaceData.speciality')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaceData.university')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='speciality',
            field=models.ManyToManyField(through='marketplaceData.UniversitySpeciality', to='marketplaceData.speciality'),
        ),
        migrations.CreateModel(
            name='BankService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('min_percent', models.FloatField()),
                ('max_percent', models.FloatField()),
                ('default_price', models.FloatField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplaceData.bank')),
            ],
        ),
    ]
