# Generated by Django 4.1.4 on 2023-07-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplaceData', '0003_alter_university_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(max_length=128),
        ),
    ]
